
const{Configuration, OpenAIApi}=require("openai");
const config = new Configuration({
    apiKey:process.env.OPENAI_API_KEY,
});

const openai = new OpenAIApi(config);


const runPrompt = async(prompt_message) =>{
    
    console.log("inside run prompt");
    let conversation = [
        {role:'system', content:' you are a mentor which provide the college detail and the information about the career only give the specified data if any other question asked then say i dont know.Provide accurate and precise answers. if anything is asked within the context but answer cannot be found then navigate to the possibilities or ask to visit college web site::https://www.tkmce.ac.in/.dont give any false answer to the question'},
        {role: 'user', content: 'This prompt contains information regarding the Computer Science Department at TKM Engineering College.The department is located in the main building near the Central Portico. The HOD room is situated close to the Seminar Hall on the ground floor, towards the left side(Room 121). On the same floor, you can find the Operating Systems Lab, towards the right side(Room 125). The second floor has the FOSS Lab and the Digital Lab on the right side, while the System Software Lab is on the left side.Furthermore, the department houses a Data Mining Lab and a librar(Room 123). The faculty rooms are 123(main building) and M315(mechanical block).Dr. Dimple A Shajahan currently serves as the HOD of the CSE Department,contact no:9447388322,email id :dimple@tkmce.ac.in. .Senior advisor of 2024 batch is Prof Aneesh G Nath. For any other queries visit the college website https://tkmce.ac.in/cse.php' },
        { role: 'user', content: 'This prompt contains information regarding the campus facilities and locations of TKM Engineering College in Kollam.The college office is situated on the first floor of the main building. Directly above the Central Portico on the first floor is the Principals office. The CSE Seminar Hall(lecture theatre), located on the ground floor of the main building(Room 120), is in close proximity to the CSE Department. Similarly, the APJ Hall can be found on the ground floor, near the basketball court. On the first floor of the main building, the Jubilee Hall is situated. Additionally, the PTA Hall is located on the ground floor, near Room 101' },
        { role: 'user', content: 'The APJ Park is situated near the front gate, offering a pleasant green space for relaxation. The Coffee Corner, located in front of the Mechanical Block, provides a convenient spot to enjoy beverages and socialize. The canteen is situated near the auditorium, serving as a dining area for students. Adjacent to the canteen is the college ground, where the Physical Education Department is located, providing space for outdoor activities and sports.The Arch Block is near the college ground.Mechanical block is near to the arch block.Next to the Mechanical Block is the Chemical Block(near kilivathil). There is an entrance to the campus hostel and a short exit called "Kilivathil" near the Mechanical Block. The area surrounding the APJ Park offers various recreational facilities, including a gym, table tennis court, tennis court, volleyball court, and squash court, catering to the students recreational needs. The basketball court can be found near the back gate, while the badminton court is located in the main building, near the APJ Hall and Room 101.Restrooms, prayer halls (separate for boys and girls), the college store, and the canteen are conveniently situated in close proximity to one another. Opposite the college store is the Workshop Block, housing civil and mechanical workshops near the quadrangle. On the first floor of the Workshop Block, is the IEDC room. The campus doctors office is located near the back gate, and an ATM service is available next to the Workshop Block. The college also has a central library situated outside the campus premises near the back gate. Additionally, each department has its own library within their respective buildings' },
        { role: 'user', content: 'This prompt contains information regarding the hostel facilities, the LH (Ladies Hostel) and Modern Hostel for girls can be easily accessed through the back gate. The Working Womens Hostel (WWH) and UGC Hostels are accessible through "Kilivathil." For boys, the Campus Hostel and Golden Jubilee Hostel are situated near the campus, with additional hostels located around Karicode. INH hostels are separate accommodations for boys, situated near the TKM School.You should be familiar with the college location karicode as well as the locations of stationary stores, food courts, and printing and photoshop stores.' },
        { role: 'user', content: 'in this prompt i give only the details aobut the civil department.The Department of Civil Engineering at TKM College of Engineering, Kollam, was established in 1958 and is one of the oldest and most dynamic engineering departments in Kerala. It offers undergraduate, postgraduate, and doctoral programs, and is recognized as a center for quality improvement by AICTE. The department receives funding for research and development activities from various organizations. It has achieved accreditation for its UG and PG programs and produces highly sought-after graduates. The department has state-of-the-art facilities, experienced faculty, and serves as a testing and consultancy center for industries. It maintains strong ties with industries and contributes to the drafting of academic syllabi. The department played a significant role in the Rebuild Kerala initiative after the floods in 2018. It organizes the International Conference on Modeling and Simulation in Civil Engineering biennially. The department also engages in social initiatives, such as rebuilding houses for flood-affected families. The success of the department is attributed to its dedicated faculty, staff, and students, as well as its commitment to continuous improvement and its vision and mission. The HOD of the Civil Engineering Department is Dr. Sajeeb R. You can contact the HOD via email at sajeeb@tkmce.ac.in or by phone at 9447908491. The HODs office is Room 107, and the faculty rooms are 110, 214, and 207. The department library is Room 119. The Civil Engineering Department at TKM College of Engineering has two main clubs: ASCE Student Chapter TKM and IE(I) Civil Chapter TKMCE. For more details, you can visit their respective Instagram pages: ASCE TKM (@asce_tkm) and IE(I) Civil TKMCE (@iei_civil_tkmce).' },
        { role:'user',content : 'in this prompt i give only the details aobut the civil department.department labs and the lab incharge dteails contact. Concrete Laboratory:Lab in Charge :Prof. Hazeena R.Associate Professor, Department of Civil Engineering Contact No : 9495974946 Email id : hazeenarrasheed@tkmce.ac.in Environmental Engineering Laboratory(room 109 ): Lab in Charge: Dr. Priya K L, Assistant Professor, Department of Civil Engineering Contact No : 9364540412 Email id : priyaram@tkmce.ac.in.,Geotechnical Engineering laboratory(117): Lab in Charge : Prof. Sulphia Beevi U, Associate Professor, Department of Civil Engineering Contact No : 8157823471 Email Id : sulphia@tkmce.ac.in, PG Advanced Computational Lab(room 118) :Lab in Charge: Dr.Adarsh. S, Associate Professor, Department of Civil Engineering Contact No : 9446915388 Email id :adarsh1982@tkmce.ac.in, Strength of materials laboratory(room 128): Lab in Charge : Prof. Rekha Ambi, Assistant Professor, Department of Civil Engineering Contact No : 9946176262 Email Id : rekha.ambi@tkmce.ac.in ,Structural Dynamics Lab: Lab in Charge : Dr. Chinsu Mereena Joy, Assistant Professor, Department of Civil Engineering Contact No : 9446571691 Email Id : chinsu@tkmce.ac.in ,Structural Enginnering Lab: Lab in Charge:Dr.Ramaswamy K P, Professor, Department of Civil Engineering Contact No:9790469400 Email id :ramaswamykp@gmail.com, Surveying lab(room 108): Lab in Charge:Dr. Muhammed Siddhik A, Assistant Professor, Department of Civil Engineering Contact No :9446162589 Email id :muhammedsiddik@tkmce.ac.in, Transportation Engineering Lab: Lab in Charge Dr. Kavitha Madhu, Associate Professor, Department of Civil Engineering Contact No 8547566336 Email id kavithamadhu@tkmce.ac.in, UG computational lab (room 203): Lab in Charge: Dr.Adarsh. S, Associate Professor, Department of Civil Engineering Contact No : 9446915388 Email id :adarsh1982@tkmce.ac.in , Water Research Laboratory(room 103): Contact Person: Dr. Priya K L, Assistant Professor, Department of Civil Engineering Contact No : 9364540412 Email id : priyaram@tkmce.ac.in, Hydroinformatics lab: Faculty in Charge: Dr.Adarsh. S, Associate Professor, Department of Civil Engineering Contact No : 9446915388 Email id :adarsh1982@tkmce.ac.in, Civil Engineering Workshop: Lab in Charge : Prof. Sruthi R. Krishnan, Assistant Professor, Department of Civil Engineering Contact No : 9446963106 Email Id : sruthirkrishnan@tkmce.ac.in'},
        {role:'user', content:'Chemical engg:Number of UG students is 271, number of Research Scholars is 1, number of publications is 60, the number of faculty is 14 and number of technical staff is 6.The HOD of chemical department is prof.Saibi.The contact details of HOD is phone number 9995718134 and emailid is saibi@tkmce.ac.in.Lboratories in the department include Chemical Technology and environmental engg. lab, particle technology lab, heat transfer operations lab, software lab, chemical reaction engineering lab, mass transfer operations lab and process control lab.The department library incharge is Mr. Muhammed Anzil P K and the library working hour is 9am to 5pm.The clubs in the department are The Institution of Engineers (India) (IEI), American Institute of Chemical Engineers (AIChe), Indian Institute of Chemical Engineers (IIChE).To know more about the department you can visit the website https://www.tkmce.ac.in/ce.php.For the palcement status of 2021-22 visit https://www.tkmce.ac.in/uploads/placement/PLACEMENT%20STATUS%202021-22.pdf.'},
        {role:'user', content:'The HOD of the physical education department is Dr.Maneesh Rasheed.The department facilities include basketball court, Cricket pitch, tennis court, football court, indoor women shuttle badminton court and a volleyball court.The department organises four home tournaments every year George joseph memorial football tournament, Ashokan memorial basketball tournament, Kutty Krishnan memorial volleyball tournament, Benny memorial volleyball tournament.Other activities include District championship, Intramural championship, Annual athletic meet every year, Coaching camp, Yoga, Aerobics,Fitness sessions, Health class.For more information about the department visit https://www.tkmce.ac.in/physical.php.'},
        {role:'user', content:'There are 4 hostels for boys and they are Trust Hostel, Campus Hostel, Golden Jubilee Hostel and International Students Hostel.There are 7 hostels for girls which are, Ladies Hostel (Main), UGC TKM Trust Hostel (A,B,C Blocks), AICTE TKM Trust Hostel, Modern Hostel, Vijaya INN ( Modern Hostel Annexe-I for PG and Research Scholars ), Working Women’s Hostel and International Hostel.Regarding the admission you can refer the pdf https://tkmce.ac.in/uploads/Hostel%20Details.pdf.For more details visit https://tkmce.ac.in/hostel.php.'},
        {role:'user', content:'Department of ECE is in the 1st floor of the main building.Number of UG students in EC department is 557. Number of PG students is 28.Number of Research Scholars is 15. Number of faculty is 26.Number of technical Staff is 8.number of publications is 239.The HOD of the department is Prof.Shabeer S and his phone number is 9447654163 and emailid is shabeer@tkmce.ac.in.Laboratories in the department include electronic devices and circiuit laboratory, digital integrated circuits laboratory, communication engineering laboratory, microprocessor/microcontroller laboratory, advanced communication laboratory, VLSI design laboratory, Electronic product design and fabrication lab, digital signal processing laboratory, departmant computing facility, PG and research laboratory.The clubs in the department are IETE, ECE Association (for more information visit https://www.ecetkmce.live/), IEEE SB TKMCE(for more information visit https://www.ieeesbtkmce.in/).114 students where placed in the year 2022.For the palcement status of 2021-22 visit https://www.tkmce.ac.in/uploads/placement/PLACEMENT%20STATUS%202021-22.pdf.To know more about the department visit the website https://www.tkmce.ac.in/ece.php, activity points:https://ktu.edu.in/eu/att/attachments.htm?download=file&id=Bf1Ie64NNlCIbQPgxzMeiqaZaITiPNKhe24NqRVOreE%3D&announcementId=m3wIwIqGuozHQ0OdieVW5qKOb3nLceuS9zOdUcOhnN4%3D&fileName=ACTIVITYPOINTS.pdf&downloadType=xSoEMOcheCmrdYCOgQOJALCA7tk2UIKVeRs2zkFGWz0%3D,club details you can wist this link:https://drive.google.com/drive/folders/1-sTkFjat6u2Ryv-3Pv-_xE5iFmkx9nyY?usp=drive_link, Subject deatils:https://drive.google.com/drive/folders/12QUpp0UdDks-VK8JsUsp2754zB85aMBA?usp=sharing'},
        {role:'user', content:'The librarian of the college central library is Dr. Ajeemsha S, email : tkmcel@gmail.com, Mobile: 9961853343,04742713933.Monday to friday the library functions from 9:30am to 9:00pm.On saturdays and holidays the working hours are from 10am to 5pm.Library offers campus login facility for all students of tkmce.Digital library is also available, you can visit https://tkmce.ac.in/library-digital.php.For more information about the central library please visit https://tkmce.ac.in/library.php.'},
        {role:'user', content:'Here i am giving some website details.For queries regarding the following data respond with the appropiate links etlab:https://www.tkmce.etlab.in/user/login ,Ktu login :https://app.ktu.edu.in/login.htm, Result checking:https://ktu.edu.in/eu/res/viewExamStudentResults.htm, placement details of seniors(2022):https://tkmce.ac.in/uploads/placement/PLACEMENT%20STATUS%202021-22.pdf , iedc:https://www.instagram.com/iedc_tkmce/, Literary and Debate Club :https://www.instagram.com/litdeb_tkmce/, Sports Club:https://www.instagram.com/tkmce_sports_fraternity/, ISTE TKMCE:https://www.instagram.com/iste_tkmce_/, Hestia (hestia is not a club it a techno cultural fest ):https://www.instagram.com/hestia.tkmce/(instagram), CSI SB TKMCE:https://www.instagram.com/csi_tkmce/, TinkerHub TKMCE: https://www.instagram.com/tinkerhub_tkmce/, CSE TKMCE:https://www.instagram.com/cse_tkmce/, , GDSC TKMCE:https://www.instagram.com/gdsc.tkmce/'},
        {role: 'user', content:'emergecy contact detail are given here: Principal 0474-2712022, 9847072024. College Office 0474-2712024, 0474-2713129, 0474-2711591. College Gate 0474-2712024 .Campus Doctor 7025055633 .College Vehicle (For Emergency) 0474-2713126. Administrative Officer 04742713126, 04742708353. Library 04742713933. Placement Cell 0474271312. Help Desk (Maintenance) 9446235854. Hospitals Medicity 0474-2721520, 2721519. N.S. Hospital 0474-2723199. District Hospital 0474-2768667. Police 100, 0474-2711155. '},
        { role: 'user', content: 'What are the upcoming hackathons or technical events at TKM College of Engineering?' },
        { role: 'assistant', content: 'Give an apology message saying you dont have access to this information' }
    ];
    
    
    
    const response= await openai.createChatCompletion({
        model:"gpt-3.5-turbo",
        messages: conversation.concat({role:'user',content:prompt_message}),
        max_tokens: 20,
        temperature: 0.2,
    
        
    });
    console.log(response.data.choices[0].message.content);
    conversation = [];
    return response.data.choices[0].message.content;
};

//runPrompt(prompt_message);

module.exports = runPrompt;
  